//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingFilm
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class KhachHang
	{
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public KhachHang()
    {
        this.DatVes = new HashSet<DatVe>();
    }

    public int MaKH { get; set; }

    public string HoTenKH { get; set; }

    [Required]
    [EmailAddress(ErrorMessage = "Invalid Email Address")]
    public string Email { get; set; }

	[Required(ErrorMessage = "The Pass field is required.")]
	public string MatKhauKH { get; set; }

    public System.DateTime NgaySinh { get; set; }

    public bool GioiTinh { get; set; }

    [Required]
    [StringLength(12, MinimumLength = 12, ErrorMessage = "CCCD must be 12 digits.")]
    [RegularExpression("^[0-9]*$", ErrorMessage = "CCCD must be numeric.")]
    public string CCCD { get; set; }

    public string DiaChi { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DatVe> DatVes { get; set; }
	}
}
