//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingFilm
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichChieu
    {
        public int MaLC { get; set; }
        public Nullable<System.DateTime> NgayChieu { get; set; }
        public Nullable<System.TimeSpan> SuatChieu { get; set; }
        public Nullable<int> MaPhim { get; set; }
    
        public virtual Phim Phim { get; set; }
    }
}
