//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingFilm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookingFilmTicketsEntities1 : DbContext
    {
        public BookingFilmTicketsEntities1()
            : base("name=BookingFilmTicketsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DatVe> DatVes { get; set; }
        public virtual DbSet<DoAn> DoAns { get; set; }
        public virtual DbSet<Ghe> Ghes { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LichChieu> LichChieux { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NVChamSoc> NVChamSocs { get; set; }
        public virtual DbSet<NVDangTai> NVDangTais { get; set; }
        public virtual DbSet<NVQuanLy> NVQuanLies { get; set; }
        public virtual DbSet<Phim> Phims { get; set; }
        public virtual DbSet<PhongChieu> PhongChieux { get; set; }
        public virtual DbSet<RapChieu> RapChieux { get; set; }
        public virtual DbSet<SuKien> SuKiens { get; set; }
        public virtual DbSet<Ve> Ves { get; set; }
    }
}
