//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingFilm
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.NVChamSocs = new HashSet<NVChamSoc>();
            this.NVDangTais = new HashSet<NVDangTai>();
            this.NVQuanLies = new HashSet<NVQuanLy>();
        }
    
        public int MaNV { get; set; }
        public string UserNameNV { get; set; }
        public string MatKhauNV { get; set; }
        public string HoTenNV { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public bool GioiTinh { get; set; }
        public string CCCD { get; set; }
        public Nullable<decimal> HeSoLuong { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> MaRC { get; set; }
    
        public virtual RapChieu RapChieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NVChamSoc> NVChamSocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NVDangTai> NVDangTais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NVQuanLy> NVQuanLies { get; set; }
    }
}
